#ifndef OIL_OILIMPLEMENTRESOLUTION_H
#define OIL_OILIMPLEMENTRESOLUTION_H

class OilNamespaceDefinition;
class OilImplementBlock;

typedef enum
{
	
	kResolveImplementsStatus_Success_Complete,
	kResolveImplementsStatus_Success_Progress,
	kResolveImplementsStatus_Success_NoProgress,
	kResolveImplementsStatus_Failure_TemplateMismatch,
	kResolveImplementsStatus_Failure_NonExistantType,
	kResolveImplementsStatus_Failure_ImplementedForNonTrait,
	kResolveImplementsStatus_Failure_ImplementingTrait,
	kResolveImplementsStatus_Failure_Conflict_PrincipalImplementation,
	kResolveImplementsStatus_Failure_Conflict_TraitImplementation_NamespaceCollision,
	kResolveImplementsStatus_Failure_Conflict_TraitImplementation_TraitCollision
	
} ResolveImplementsStatus;

ResolveImplementsStatus OilResolveImplements ( OilNamespaceDefinition & GlobalNS );

#endif
