#ifndef FLOATINGPOINT_DEFINITIONS_H
#define FLOATINGPOINT_DEFINITIONS_H

#define F32_EXPONENT_WIDTH 8
#define F32_EXPONENT_OFFSET - 127
#define F32_FRACTION_WIDTH 23

#define F64_EXPONENT_WIDTH 11
#define F64_EXPONENT_OFFSET - 1023
#define F64_FRACTION_WIDTH 52

#endif
